rev make

diff --git a/src/makefile b/src/makefile
--- a/src/makefile
+++ b/src/makefile
@@ -5,48 +5,68 @@
 ## -- -- VARS -- --
 
 pg_io  =/tmp/pg_io
+lockpath = /var/gits/_lock-mkStatus
 
 pg_uri_root =postgres://postgres@localhost
-pg_db       =dl03t_main
-pg_dbingest =ingest1
+
+## danger dl03t_main, ingest1. Use dummy 99 to test.
+pg_db       =dl99t_main
+pg_dbingest =ingest99
+
 pg_uri      =$(pg_uri_root)/$(pg_db)
 pg_uringest =$(pg_uri_root)/$(pg_dbingest)
 
 countries = "'BR','CL','CO','EC','PE','VE'"  # em uso e conforme data/jurisdiction.csv
 
 gits_basepath = /var/gits
+pk_basepath = $(gits_basepath)/_dg
 
 DB_TEST := $(shell psql $(pg_uri_root) -c "\l" | awk '/$(pg_dbingest)/ {n=(n>0)?3:1} /$(pg_db)/ {n=(n>0)?3:2} END {print n;}')
 DB_TEST2 := $(shell echo '/$(pg_dbingest)/ {n=(n>0)?3:1} /$(pg_db)/ {n=(n>0)?3:2} END {print n;}')
 
-## -- -- RULES -- --
+## -- CONFIGS --
+.SILENT: message countpacks status_disk_abuse
 
-all:
-	@echo "--------  make do projeto Preserv  ----------"
-	@echo "Use primeiro   sudo make permissions"
-	@echo "Use depois     make ini_all"
-	@echo "!Importante para users deste projeto:"
-	@echo "   sudo usermod -a -G postgres masterUser"
-	@echo "   sudo usermod -a -G www-data masterUser"
+## ## ## ## ##
+## -- HELP --
+message:
+	echo "--------  make of the Preserv project ----------"
+	echo
+	echo " -- SQL BUILDERs --"
+	echo " ini_all: configure and prepare all basic databases and schemas"
+	echo " ini_sql_db: ..."
+	echo
+	echo " -- REPORT tools --"
+	echo " countpacks [pkdir=v]: count package-evidence files ok pkdir (e.g. preserv-BR) or its root"
+	echo " status: of databases and disk usage"
+	echo
+	echo " -- ADMIN tools --"
+	echo " fix_usergroup username=v: add standard groups to username"
+	echo " fix_permissions: execute chmod and chown in the standard folders"
+	echo
+
+## ## ## ## ##
+## -- -- SQL BUILDERs -- --
+
+all: ini_all
 
 ini_all: ini_sql_db ini_sql
 
 ini_sql_db:
-	@echo "... Verificando bancos de dados"
+	@echo "... Checking databases"
 ifneq ($(DB_TEST),$(filter $(DB_TEST),1 3))
-	@echo "... Criando banco $(pg_dbingest)"
+	@echo "... Creating database $(pg_dbingest)"
 	psql $(pg_uri_root) -c "CREATE DATABASE $(pg_dbingest)"
 endif
 ifneq ($(DB_TEST),$(filter $(DB_TEST),3 2))
-	@echo "... Criando banco $(pg_db)"
+	@echo "... Creating database $(pg_db)"
 	psql $(pg_uri_root) -c "CREATE DATABASE $(pg_db)"
 endif
-	@echo "Bases $(pg_db) e $(pg_dbingest) criadas."
+	@echo "Databases $(pg_db) and $(pg_dbingest) created."
 
-ini_sql: $(gits_basepath)/_a4a/pg_pubLib-v1/src/makefile
+ini_sql: pgio lck $(gits_basepath)/_a4a/pg_pubLib-v1/src/makefile
 	@echo "--- Preparing filesystem... ---"
-	rm -f /opt/lock-mkStatus/digitalPreservation-makeSQL.~feito
-	mkdir -p $(pg_io)
+	rm -f $(lockpath)/digitalPreservation-makeSQL.~feito
 	@echo "--- Preparing databses... ---"
 	@echo "--- Running SQL pubLib ---"
 	cd $(gits_basepath)/_a4a/pg_pubLib-v1/src; make all pg_db=$(pg_db)
@@ -61,30 +81,58 @@ ini_sql: $(gits_basepath)/_a4a/pg_pubLib-v1/src/makefile
 	psql $(pg_uri) < eclusa/step1-ini.sql
 	# sh eclusa-step2a-ins.sh
 	#/var/gits/WS/src? psql $(pg_uri) < eclusa/step2b-ins.sql
-	touch /opt/lock-mkStatus/digitalPreservation-makeSQL.~feito
+	touch $(lockpath)/digitalPreservation-makeSQL.~feito
+	chmod 666 $(lockpath)/digitalPreservation-makeSQL.~feito
 
-## GENERAL CHECKs:
+## ## ## ## ##
+## -- -- REPORT tools -- --
 
-countpacks: $(pkdir)
-	@echo "---- Counting lines of $(dir) ----"
-	@echo "* sha256sum.txt files:"
-	@find $(pkdir) -name "sha256sum.txt" | wc -l
-	@echo "* _pk* directories:"
-	@(cd $(pkdir); find . -type d  -wholename "./*/*/*/_pk*" | wc -l)
-	@echo "* README.md files:"
-	@find $(pkdir) -name "README.md" | wc -l
-	@echo "* make_conf files:"
-	@find $(pkdir) -name "make_conf.*" | wc -l
+countpacks: $(pk_basepath)
+	echo "---- Counting lines of $(pk_basepath)/$(pkdir) ----"
+	echo "* sha256sum.txt files:"
+	find $(pk_basepath)/$(pkdir) -name "sha256sum.txt" | wc -l
+	echo "* _pk* directories:"
+	(cd $(pk_basepath)/$(pkdir); find . -type d  -wholename "./*/*/*/_pk*" | wc -l)
+	echo "* README.md files:"
+	find $(pk_basepath)/$(pkdir) -name "README.md" | wc -l
+	echo "* make_conf files:"
+	find $(pk_basepath)/$(pkdir) -name "make_conf.*" | wc -l
 
+status: status_base status_disk_abuse
 
+status_base:
+	psql $(pg_uri_root) -c "\l+"
+
+status_schEtc:
+	@echo "-- database ingest1:"
+	psql $(pg_uri)/ingest1    -c "\dn"
+	@echo "-- OSM testing database DL01t_osm:"
+	psql $(pg_uri)/dl01t_osm  -c "\dn"
+	@echo "-- MAIN testing database DL03t_main:"
+	psql $(pg_uri)/dl03t_main -c "\dn"
+
+status_schProd:
+	@echo "-- -- -- ON-PRODUCTION SCHEMAS -- -- --"
+	@echo "-- OSM stable database DL02s_osm:"
+	psql $(pg_uri)/dl02s_osm  -c "\dn"
+	@echo "-- MAIN stable database DL04s_main:"
+	psql $(pg_uri)/dl04s_main -c "\dn"
+
+status_disk_abuse:
+	echo "-- -- -- CHECK disk usage ABUSE -- -- --"
+	(du -h $(gits_basepath)  | grep -v "^[0-9][0-9,\.]*[KM]") || true
+	# (du -h /var/www | grep -v "^[0-9][0-9,\.]*[KM]") || true
+	(du -h $(pg_io)     | grep -v "^[0-9][0-9,\.]*[KM]") || true
+	echo "... if no line, it is ok!"
+
+## ## ## ##
 ## ECLUSA, commands to execute by root at crontab:
 
-ecl_run: /opt/lock-mkStatus/digitalPreservation-makeSQL.~feito
+ecl_run: pgio $(lockpath)/digitalPreservation-makeSQL.~feito
 	whoami
 	pwd
 	@echo "Run with sudo! (idempotent)"
-	mkdir -p $(pg_io)
-	chown postgres:postgres -R $(pg_io)
+	sudo bash fixaPermissoes.sh $(pg_io)
 	# make -C /var/gits/WS/src ini_tmprefresh
 	psql $(pg_uri) -c "SELECT optim.fdw_wgets_script('refresh')"
 	sh $(pg_io)/run_wgets-refresh.sh
@@ -92,22 +140,20 @@ ecl_run: /opt/lock-mkStatus/digitalPreservation-makeSQL.~feito
 	sh /var/gits/digital-preservartion/src/eclusa/mkCpHashFiles.sh
 	psql $(pg_uri) -c "SELECT * FROM eclusa.vw03alldft_cityfolder_ins" # insert into origin
 
-ecl_out: ecl_run
-	# testar se $$(pg_io) funciona
+ecl_out: pgio ecl_run
 	psql $(pg_uri) -c "COPY (SELECT * FROM optim.vwdump_origin) TO '$$(pg_io)/br-origin.csv' CSV HEADER"
 	# tem API nao precisa disso?
 
 # core inserts
-ini_ins:
-	@echo "run SQL spcripts"
-	mkdir -p $(pg_io)
+ini_ins: pgio
+	@echo "run SQL spcripts:"
 	psql $(pg_uri) -c "SELECT optim.fdw_wgets_script()"
 	sh $(pg_io)/run_wgets-all.sh
   # falta rodar resto
 
 
 ## testing ... correct is to wget
-ins_step1: # LIXO
+ins_step1: pgio # LIXO
 	mkdir -p $(pg_io)/digital-preservartion-XX
 	rm -f $(pg_io)/digital-preservartion-XX/*.csv
 	for gitdir in /var/gits/digital-preservartion-*; do \
@@ -117,6 +163,8 @@ ins_step1: # LIXO
 	done
 
 ##############
+## ## ## ##
+## LIXO? commands to execute by root at crontab:
 
 # Tests "load and check" of first-level local jurisdictions, maintained by Wikidata and OSM:
 jurisdiction_iso_prepare:  # depends on prepared databases
@@ -124,14 +172,14 @@ jurisdiction_iso_prepare:  # depends on prepared databases
 	psql $(pg_uringest) -c "CREATE SCHEMA IF NOT EXISTS optim; DROP TABLE optim.jurisdiction;"
 	pg_dump --format plain --table optim.jurisdiction $(pg_uri)  | psql $(pg_uringest)
 
-jurisdiction_iso_run: jurisdiction_iso_prepare jurisdiction/get.sh jurisdiction/get.sql run_mustache.py jurisdiction/getWikidata.mustache
+jurisdiction_iso_run: pgio jurisdiction_iso_prepare jurisdiction/get.sh jurisdiction/get.sql run_mustache.py jurisdiction/getWikidata.mustache
 	@echo "--- Jurisdiction prepare bash file and LOAD ---"
 	sh jurisdiction/get.sh
 	ls -l /tmp/pg_io/wdquery-*.csv
 	psql $(pg_uringest) < jurisdiction/get.sql
 
 # edit SQL and run:
-jurisdiction_iso_run2:  get-Latam5.sql get-Latam5.sh run_mustache.py getWikidata.mustache
+jurisdiction_iso_run2: pgio get-Latam5.sql get-Latam5.sh run_mustache.py getWikidata.mustache
 	@echo "--- Jurisdiction prepare2 bash file and LOAD ---"
 	sh jurisdiction/get.sh
 	ls -l /tmp/pg_io/wdquery-*.csv
@@ -152,7 +200,7 @@ jurisdiction_iso_test:
 	 WHERE osm_id IN (SELECT osm_id FROM rec_ids) order by 1\
 	"
 
-redirects_update:
+redirects_update: pgio
 	@echo "-- Atualiza redirecionamentos --"
 	@echo Download da tabela de-para ....
 	wget "https://docs.google.com/spreadsheets/d/1CL6f0I9DSpqKxKC7QNJGCfyabq7mDOVab5QBGV5VLOk/gviz/tq?tqx=out:csv&sheet={de-para}" -O "$(pg_io)/de-para.csv"
@@ -172,11 +220,7 @@ codec_type_prepare:
 	@echo "--- codec_type load ---"
 	psql $(pg_uringest) -c "SELECT ingest.load_codec_type('$(gits_basepath)/_dg/preserv/data/codec_type.csv',',');"
 
-fix_permissions:
-	@echo "... Fixando permissões padronizadas:"
-	sudo bash fixaPermissoes.sh /var/gits /tmp/pg_io
-
-load_license_tables:
+load_license_tables: pgio
 	@echo "-- Carrega tabelas --"
 # 	wget "https://raw.githubusercontent.com/ppKrauss/licenses/master/data/families.csv" -O "$(pg_io)/families.csv"
 	wget "https://raw.githubusercontent.com/ppKrauss/licenses/master/data/licenses.csv" -O "$(pg_io)/licenses.csv"
@@ -194,3 +238,26 @@ load_license_tables:
 	LEFT JOIN tmp_donatedPackold2new AS t \
 	ON d.pack_id = t.pack_id;\
 	DROP FOREIGN TABLE IF EXISTS tmp_licenses; DROP FOREIGN TABLE IF EXISTS tmp_implieds; DROP FOREIGN TABLE IF EXISTS tmp_donatedPack; DROP FOREIGN TABLE IF EXISTS tmp_donatedPackold2new;"
+
+## ## ## ##
+## -- ADMIN FIX TOOLS --
+fix_permissions: pgio
+	@echo "... Fixing standard permissions, as sudor:"
+	sudo bash fixaPermissoes.sh /var/gits /tmp/pg_io
+
+fix_usergroup:
+	@echo "... Adding standard usergroups, as sudor:"
+ifeq ($(username),)
+	@echo "Target error: please say username"
+else
+	@echo "... Addding to $(username):"
+	sudo usermod -a -G postgres $(username)
+	sudo usermod -a -G www-data $(username)
+endif
+
+## ## ## ##
+## AUXILIAR TARGETS, snippet code for reuse
+pgio:
+	mkdir -p $(pg_io)
+lck:
+	mkdir -p $(lockpath)
